version: "3.8"

services:
  postgres:
    container_name: delliv
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: delliv

  react-app:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
