@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gustavo Gomes",
  "email": "gustavo@delliv.com.br",
  "password": "12345678",
  "address": "rua joao urizzi 421"

}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "gustavo@delliv.com.br",
  "password": "12345678"
}

###



POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{

  "total": 0,
  "itens": [

    {
      "productId": "839453b5-80ad-42d9-9a2b-ab60898e68a0",
      "quantity": 5
    }
  ]
}

###

GET {{baseUrl}}/products
content-type: application/json
Authorization: Bearer {{authToken}}

###

PUT {{baseUrl}}/orders/a0c15170-da92-4384-b860-7ebc16a5f55a/status
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "status": "READY"
}
###

POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Produto 1",
  "price": 10,
  "category": "Categoria 1",
  "description": "Descrição do produto 1"
}

